language: clojure
lein: 2.9.3
jdk:  # We only use OpenJDKs because of these shenanigans: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html
  - openjdk8
  - openjdk11
  - openjdk14

script: lein do git-info-edn, check
