# Prerequisites:
# ./certs folder exists and contains bot user cert and truststore
# ./config.edn file exists
# For more details, check README.md

version: '2'
services:
 bot-clj:
   restart: always
   build: .
   volumes:
    - ./etc:/etc/opt/bot-clj:ro
